### ISSUE TITLE
SGD Optimizer

### ISSUE THREAD

**Issue by mplatzer** [tuwien-musicir/DL_Tutorial#3]
in most of the examples SGD is used as optimizer. any reason not to use a "smarter" one, like adam in these cases?

**Comment by audiofeature** [comment]
The "reason" is that we wanted to start with simple, standard setups, and SGD is the "traditional" method. I had planned to add the "smarter" ones in a later tutorial, but did not do so (yet). But of course you may replace the SGD by "smarter" ones. (although they do not always work better on this "toy data set".

**Comment by mplatzer** [comment]
i see. from end-user perspective `optimizer = 'sgd'` is just as simple as `optimizer = 'adam'`, that's why I thought one should point even newbies to these more sophisticated optimizers. unless of course, if they indeed do harm in these toy examples.
